export const ENTERPRISE_STATUS_LABELS = Object.freeze({
  visitor: Object.freeze({
    PENDING: "Pending approval",
    APPROVED: "Approved",
    REJECTED: "Denied",
    CHECKED_IN: "Checked in",
    CHECKED_OUT: "Checked out",
    EXPIRED: "Expired",
    SUSPENDED: "Suspended",
  }),
  invite: Object.freeze({
    INVITED: "Invited",
    PRE_REGISTRATION_PENDING: "Pre-registration pending",
    PRE_REGISTERED: "Pre-registered",
    PENDING_APPROVAL: "Pending approval",
    APPROVED: "Approved",
    BADGE_ISSUED: "Badge issued",
    QR_ISSUED: "Badge issued",
    REJECTED: "Denied",
    DENIED: "Denied",
    CHECKED_IN: "Checked in",
    ARRIVED: "Checked in",
    CHECKED_OUT: "Checked out",
    EXPIRED: "Expired",
    REVOKED: "Revoked",
  }),
  workforce: Object.freeze({
    ACTIVE: "Active",
    PRESENT: "Checked in",
    IN: "Checked in",
    OUT: "Checked out",
    OUTSIDE: "Checked out",
    UNVERIFIED: "Unverified",
    PENDING_APPROVAL: "Pending approval",
    CHANGES_REQUESTED: "Changes requested",
    REJECTED: "Denied",
    DENIED: "Denied",
    INACTIVE: "Disabled",
    DISABLED: "Disabled",
    LOCKED: "Locked",
  }),
});

export const ENTERPRISE_STATUS_TONES = Object.freeze({
  APPROVED: "success",
  ACTIVE: "success",
  BADGE_ISSUED: "success",
  QR_ISSUED: "success",
  CHECKED_IN: "success",
  INSIDE: "success",
  IN: "success",
  PRESENT: "success",
  VALID: "success",
  SUCCESS: "success",
  PENDING: "warning",
  PENDING_APPROVAL: "warning",
  PRE_REGISTERED: "warning",
  CHANGES_REQUESTED: "warning",
  LATE: "warning",
  NOT_ACTIVE_YET: "warning",
  OVERDUE_VISIT: "warning",
  SUSPENDED: "danger",
  WARNING: "warning",
  REJECTED: "danger",
  DENIED: "danger",
  DISABLED: "danger",
  INACTIVE: "danger",
  LOCKED: "danger",
  EXPIRED: "danger",
  REVOKED: "danger",
  CANCELLED: "danger",
  SUSPENDED_VISITOR: "danger",
  DANGER: "danger",
  CHECKED_OUT: "neutral",
  OUT: "neutral",
  OUTSIDE: "neutral",
  UNVERIFIED: "neutral",
  INVITED: "info",
  PRE_REGISTRATION_PENDING: "info",
  SENT: "info",
  VIEWED: "info",
  EXPORT: "info",
  REPORT: "info",
  AUDIT: "info",
  INFO: "info",
  DEFAULT: "neutral",
  NEUTRAL: "neutral",
});

export const ENTERPRISE_WORKFLOW_LABELS = Object.freeze({
  visitorOperations: "Visitor Operations",
  workforceOperations: "Workforce Operations",
  approvalQueue: "Approval Queue",
  liveRegister: "Live Register",
  badgeAndQr: "Badge and QR",
  operationalAlerts: "Operational Alerts",
});
