import { prepareOperationalReportExport } from "./accessService.js";
import { escapeHtml } from "./portalShell.js";

export const OPERATIONAL_REPORTS = Object.freeze([
  { type: "visitor-register", title: "Visitor Register", note: "Approved, pending, checked-in, and historical visitor access records." },
  { type: "operational-summary", title: "Operational Summary", note: "Audit-safe access, approval, and checkpoint activity." },
  { type: "workforce-activity", title: "Workforce Activity Report", note: "Employee presence, check-in, check-out, and guard actions." },
  { type: "incident-report", title: "Security Incident Report", note: "Emergency, suspicious activity, and security incident records." },
  { type: "denied-entry-report", title: "Denied Entry Report", note: "Rejected visitor requests and denied checkpoint outcomes." },
  { type: "checkpoint-activity", title: "Checkpoint Activity Report", note: "Recent operational audit trail for security checkpoints." },
]);

export const SECURITY_REPORTS = Object.freeze([
  OPERATIONAL_REPORTS.find((report) => report.type === "operational-summary"),
  OPERATIONAL_REPORTS.find((report) => report.type === "incident-report"),
  OPERATIONAL_REPORTS.find((report) => report.type === "denied-entry-report"),
  OPERATIONAL_REPORTS.find((report) => report.type === "checkpoint-activity"),
].filter(Boolean));

export async function exportOperationalReport(basePath, reportType, format) {
  const response = await prepareOperationalReportExport(basePath, reportType, format);
  const report = response?.data || response;
  downloadPreparedReport(report);
  return report;
}

export function downloadPreparedReport(report) {
  const normalizedFormat = String(report?.format || "CSV").toUpperCase();
  const filename = `${slugify(report?.title || report?.reportType || "accessflow-report")}-${new Date(report?.generatedAt || Date.now()).toISOString().slice(0, 10)}`;
  if (normalizedFormat === "PDF") {
    const printWindow = window.open("", "_blank", "noopener,noreferrer");
    if (!printWindow) {
      throw new Error("Allow pop-ups to generate the PDF report.");
    }
    printWindow.document.write(reportHtml(report));
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
    return;
  }

  const blob = new Blob([reportCsv(report)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

export function reportCsv(report) {
  const columns = Array.isArray(report?.columns) && report.columns.length ? report.columns : inferColumns(report?.rows || []);
  const header = columns.map((column) => csvCell(column.label)).join(",");
  const rows = (report?.rows || []).map((row) => columns.map((column) => csvCell(row[column.key])).join(","));
  return [
    `AccessFlow ${report?.title || "Operational Report"}`,
    `Generated At,${csvCell(report?.generatedAt)}`,
    `Generated By,${csvCell(report?.generatedBy)}`,
    `Organization,${csvCell(report?.organizationName || report?.organizationId || "Platform")}`,
    "",
    header,
    ...rows,
  ].join("\n");
}

export function reportHtml(report) {
  const columns = Array.isArray(report?.columns) && report.columns.length ? report.columns : inferColumns(report?.rows || []);
  const summary = Object.entries(report?.summary || {}).map(([key, value]) => `
    <article><span>${escapeHtml(label(key))}</span><strong>${escapeHtml(value)}</strong></article>
  `).join("");
  const rows = (report?.rows || []).slice(0, 300).map((row) => `
    <tr>${columns.map((column) => `<td>${escapeHtml(row[column.key])}</td>`).join("")}</tr>
  `).join("");
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report?.title || "Operational Report")}</title><style>
    body{background:#071120;font-family:Inter,Arial,sans-serif;margin:32px;color:#f8fafc}
    header{border-bottom:2px solid #2563eb;margin-bottom:20px;padding-bottom:14px}
    h1{font-size:28px;margin:0 0 6px}p{color:#94a3b8;margin:4px 0}
    section{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin:18px 0}
    article{background:linear-gradient(180deg,#0b1730,#0a1628);border:1px solid rgba(79,140,255,.18);border-radius:8px;padding:10px}
    span{display:block;color:#64748b;font-size:10px;text-transform:uppercase}strong{display:block;font-size:18px;margin-top:6px}
    table{border-collapse:collapse;font-size:10px;width:100%}th,td{border:1px solid rgba(79,140,255,.18);padding:6px;text-align:left;vertical-align:top}
    th{background:#0b1730;color:#f8fafc}footer{color:#64748b;font-size:10px;margin-top:18px}
  </style></head><body><header><h1>${escapeHtml(report?.title || "Operational Report")}</h1><p>Generated ${escapeHtml(report?.generatedAt || "")} by ${escapeHtml(report?.generatedBy || "AccessFlow")}</p><p>${escapeHtml(report?.organizationName || report?.organizationId || "Platform scope")}</p></header><section>${summary}</section><table><thead><tr>${columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><footer>AccessFlow operational export ${escapeHtml(report?.exportId || "")}. Generated for audit-safe review.</footer></body></html>`;
}

function inferColumns(rows) {
  return Object.keys(rows[0] || {}).map((key) => ({ key, label: label(key) }));
}

function csvCell(value) {
  const text = value == null ? "" : String(value);
  return `"${text.replaceAll('"', '""')}"`;
}

function label(value) {
  const spaced = String(value || "Field").replaceAll(/([a-z])([A-Z])/g, "$1 $2").replaceAll(/[-_]+/g, " ");
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function slugify(value) {
  return String(value || "accessflow-report").toLowerCase().replaceAll(/[^a-z0-9]+/g, "-").replaceAll(/^-|-$/g, "") || "accessflow-report";
}
