export const ROUTE_DEFINITIONS = {
  dashboard: {
    slug: "dashboard",
    navLabel: "Dashboard",
    eyebrow: "Organization Operations",
    title: "Operations Dashboard",
    description: "Track visitor flow, workforce presence, approvals, and daily organization activity in one focused workspace.",
    badges: ["Organization scoped", "Daily operations", "Admin workspace"],
  },
  employees: {
    slug: "employees",
    navLabel: "Employees",
    eyebrow: "Workforce Directory",
    title: "Employee Management",
    description: "Create employee and security accounts, manage organization access, and keep workforce identity scoped to this organization.",
    badges: ["Organization scoped", "Workforce access", "Department aware"],
  },
  departments: {
    slug: "departments",
    navLabel: "Departments",
    eyebrow: "Workforce Structure",
    title: "Department Workspace",
    description: "Keep department options clean, tenant-scoped, and fast to manage without drifting into platform administration.",
    badges: ["Organization scoped", "Operational setup", "Assignment ready"],
  },
  "visitor-access": {
    slug: "visitor-access",
    navLabel: "Visitor Access",
    eyebrow: "Live Operations",
    title: "Visitor Access Workspace",
    description: "Run live visitor registration, approvals, check-ins, and record management for this organization.",
    badges: ["Organization scoped", "Frontline workflows", "Live records"],
  },
  "workforce-approvals": {
    slug: "workforce-approvals",
    navLabel: "Workforce Approvals",
    eyebrow: "Access Activation",
    title: "Workforce Approval Workspace",
    description: "Approve security-assisted worker onboarding, assign final access details, and keep QR activation admin-controlled.",
    badges: ["Organization admin", "QR activation", "Audit logged"],
  },
  "attendance-presence": {
    slug: "attendance-presence",
    navLabel: "Attendance / Presence",
    eyebrow: "Workforce Presence",
    title: "Attendance and Presence",
    description: "Review employee presence, check-in history, and active workforce coverage for this organization.",
    badges: ["Organization scoped", "Presence logs", "Workforce visibility"],
  },
  "emergency-ops": {
    slug: "emergency-ops",
    navLabel: "Emergency Ops",
    eyebrow: "Emergency Workflows",
    title: "Emergency Operations",
    description: "Run lockdown controls, broadcasts, evacuation review, and incident monitoring with the same backend workflow used by mobile.",
    badges: ["Organization scoped", "Incident response", "Realtime workflow"],
  },
  reports: {
    slug: "reports",
    navLabel: "Reports",
    eyebrow: "Organization Reports",
    title: "Reports Workspace",
    description: "Review organization-level audit events, exports, and operational reporting without platform controls.",
    badges: ["Organization scoped", "Audit visibility", "Operational reports"],
  },
  notifications: {
    slug: "notifications",
    navLabel: "Notifications",
    eyebrow: "Operational Alerts",
    title: "Notifications",
    description: "Review recent visitor, approval, and workforce notifications for this organization.",
    badges: ["Organization scoped", "Unread alerts", "Action history"],
  },
  "organization-settings": {
    slug: "organization-settings",
    navLabel: "Organization Settings",
    eyebrow: "Organization Identity",
    title: "Organization Settings",
    description: "View organization identity, timezone, active departments, and admin-scoped configuration.",
    badges: ["Organization scoped", "Tenant identity", "Settings overview"],
  },
  "platform-analytics": {
    slug: "platform-analytics",
    navLabel: "Platform Analytics",
    eyebrow: "Global Control Plane",
    title: "Platform Analytics",
    description: "Monitor multi-tenant usage, tenant activity, runtime signals, and system-wide adoption from the platform layer.",
    badges: ["Platform scope", "Multi-tenant", "Global analytics"],
  },
  organizations: {
    slug: "organizations",
    navLabel: "Organizations",
    eyebrow: "Tenant Lifecycle",
    title: "Organization Management",
    description: "Create, inspect, and govern tenant workspaces with organization-level drill-downs and safe lifecycle controls.",
    badges: ["Platform owner", "Tenant lifecycle", "Global scope"],
  },
  "tenant-health": {
    slug: "tenant-health",
    navLabel: "Tenant Health",
    eyebrow: "Tenant Operations",
    title: "Tenant Health",
    description: "Track active tenants, paused organizations, admin coverage, and tenant readiness across the platform.",
    badges: ["Platform scope", "Tenant readiness", "Health signals"],
  },
  "global-audit": {
    slug: "global-audit",
    navLabel: "Global Audit Logs",
    eyebrow: "Governance",
    title: "Global Audit Logs",
    description: "Review platform-wide audit visibility and security oversight without entering organization operator workflows.",
    badges: ["Platform scope", "Global audit", "Governance"],
  },
  "workforce-oversight": {
    slug: "workforce-oversight",
    navLabel: "Workforce Oversight",
    eyebrow: "Cross-Tenant Identity",
    title: "Workforce Oversight",
    description: "Inspect workforce and admin access across tenants from a read-heavy platform governance view.",
    badges: ["Platform scope", "Cross-tenant", "Read-heavy oversight"],
  },
  "security-monitoring": {
    slug: "security-monitoring",
    navLabel: "Security Monitoring",
    eyebrow: "Security Operations",
    title: "Security Monitoring",
    description: "Watch suspicious activity, privileged events, and security-sensitive system signals across organizations.",
    badges: ["Platform scope", "Security signals", "Privileged events"],
  },
  "platform-settings": {
    slug: "platform-settings",
    navLabel: "Platform Settings",
    eyebrow: "Platform Controls",
    title: "Platform Settings",
    description: "Manage public platform experience controls and global AccessFlow configuration surfaces.",
    badges: ["Platform owner", "Global settings", "Controlled changes"],
  },
  "system-monitoring": {
    slug: "system-monitoring",
    navLabel: "System Monitoring",
    eyebrow: "Infrastructure Visibility",
    title: "System Monitoring",
    description: "Keep runtime status, service configuration, and operational health visible at the platform layer.",
    badges: ["Platform scope", "Service health", "Infrastructure"],
  },
  "runtime-status": {
    slug: "runtime-status",
    navLabel: "Runtime Status",
    eyebrow: "Runtime",
    title: "Runtime Status",
    description: "Inspect active profile, deployment posture, upload readiness, email delivery, and rate-limit configuration.",
    badges: ["Platform scope", "Runtime posture", "Deployment visibility"],
  },
  "feature-flags": {
    slug: "feature-flags",
    navLabel: "Feature Flags",
    eyebrow: "Governance",
    title: "Feature Flags",
    description: "Prepare controlled feature rollout visibility without exposing tenant operator workflows.",
    badges: ["Platform scope", "Future ready", "Governed rollout"],
  },
  "api-health": {
    slug: "api-health",
    navLabel: "API Health",
    eyebrow: "API Operations",
    title: "API Health",
    description: "Verify API status, integration readiness, CORS posture, and service dependency health.",
    badges: ["Platform scope", "API health", "Service readiness"],
  },
};

export function buildPortalProfile(session = {}) {
  const roles = Array.isArray(session.roles) ? session.roles : [];
  return roles.includes("SUPER_ADMIN") ? SUPER_ADMIN_PROFILE : ADMIN_PROFILE;
}

const ADMIN_PROFILE = {
  key: "organization-admin",
  requiredRole: "ADMIN",
  shellClass: "org-admin-shell",
  sidebarLabel: "Organization admin navigation",
  brandLabel: "Organization operations home",
  topbarEyebrow: "Organization access",
  topbarTitle: "Organization Operations",
  topbarTagline: "Employees, visitors, approvals, and daily presence for one organization.",
  sidebarTagline: "Focused visitor and workforce operations.",
  sidebarProduct: "AccessFlow organization workspace",
  identityClass: "user-chip--organization",
  identityScope: "Organization admin",
  contextLabel: (session) => session.organizationName || session.organizationCode || "Organization",
  defaultRoute: "dashboard",
  routes: [
    "dashboard",
    "employees",
    "departments",
    "visitor-access",
    "workforce-approvals",
    "attendance-presence",
    "emergency-ops",
    "reports",
    "notifications",
    "organization-settings",
  ],
  navSections: [
    { label: "Operate", routes: ["dashboard", "visitor-access", "workforce-approvals", "attendance-presence", "emergency-ops"] },
    { label: "Workforce", routes: ["employees", "departments"] },
    { label: "Review", routes: ["reports", "notifications", "organization-settings"] },
  ],
  aliases: {
    analytics: "dashboard",
    users: "employees",
    employee: "employees",
    employees: "employees",
    "attendance": "attendance-presence",
    "presence": "attendance-presence",
    "emergency": "emergency-ops",
    "incidents": "emergency-ops",
    "organization": "organization-settings",
    "settings": "organization-settings",
  },
};

const SUPER_ADMIN_PROFILE = {
  key: "super-admin",
  requiredRole: "SUPER_ADMIN",
  shellClass: "super-admin-shell",
  sidebarLabel: "Platform owner navigation",
  brandLabel: "Platform control plane home",
  topbarEyebrow: "Global control plane",
  topbarTitle: "Platform Control Plane",
  topbarTagline: "Tenant lifecycle, governance, security, and runtime visibility across AccessFlow.",
  sidebarTagline: "Global governance and multi-tenant control.",
  sidebarProduct: "AccessFlow enterprise control plane",
  identityClass: "user-chip--platform",
  identityScope: "Platform owner",
  contextLabel: () => "Global platform",
  defaultRoute: "platform-analytics",
  routes: [
    "platform-analytics",
    "organizations",
    "tenant-health",
    "global-audit",
    "workforce-oversight",
    "security-monitoring",
    "platform-settings",
    "system-monitoring",
    "runtime-status",
    "feature-flags",
    "api-health",
  ],
  navSections: [
    { label: "Govern", routes: ["platform-analytics", "organizations", "tenant-health", "global-audit"] },
    { label: "Oversee", routes: ["workforce-oversight", "security-monitoring"] },
    { label: "Operate Platform", routes: ["platform-settings", "system-monitoring", "runtime-status", "feature-flags", "api-health"] },
  ],
  aliases: {
    analytics: "platform-analytics",
    dashboard: "platform-analytics",
    reports: "global-audit",
    audit: "global-audit",
    monitoring: "system-monitoring",
    "homepage-controls": "platform-settings",
    "homepage-settings": "platform-settings",
    users: "workforce-oversight",
  },
};

export const ROUTE_ICON_PATHS = {
  dashboard: "M4 13h6V5H4Zm0 6h6v-4H4Zm8 0h8v-8h-8Zm0-10h8V5h-8Z",
  employees: "M8 11a3 3 0 1 0-3-3 3 3 0 0 0 3 3Zm8 0a3 3 0 1 0-3-3 3 3 0 0 0 3 3ZM3 20a5 5 0 0 1 10 0Zm8.5 0a5 5 0 0 1 9.5 0Z",
  departments: "M4 5h16v4H4Zm0 5h10v4H4Zm0 5h16v4H4Z",
  "visitor-access": "M12 12a4 4 0 1 0-4-4 4 4 0 0 0 4 4Zm-7 8a7 7 0 0 1 14 0Z",
  "workforce-approvals": "M12 12a4 4 0 1 0-4-4 4 4 0 0 0 4 4Zm-7 8a7 7 0 0 1 14 0Zm13-8 2 2 4-4 1.4 1.4L20 17l-3.4-3.4Z",
  "attendance-presence": "M4 19h16v2H4Zm2-8h3v6H6Zm5-6h3v12h-3Zm5 3h3v9h-3Z",
  "emergency-ops": "M12 2 2 21h20Zm0 6 1 6h-2Zm0 10a1.3 1.3 0 1 1 0-2.6 1.3 1.3 0 0 1 0 2.6Z",
  reports: "M5 3h14v18H5Zm4 5h6v2H9Zm0 4h6v2H9Zm0 4h3v2H9Z",
  notifications: "M12 22a2.4 2.4 0 0 0 2.3-1.8H9.7A2.4 2.4 0 0 0 12 22Zm7-5-2-2v-4a5 5 0 0 0-10 0v4l-2 2v1h14Z",
  "organization-settings": "M4 5h7v14H4Zm9 0h7v6h-7Zm0 8h7v6h-7Z",
  "platform-analytics": "M4 19h16v2H4Zm2-8h3v6H6Zm5-6h3v12h-3Zm5 3h3v9h-3Z",
  organizations: "M4 5h7v14H4Zm9 0h7v6h-7Zm0 8h7v6h-7Z",
  "tenant-health": "M12 2 4 5v6c0 5 3.4 9.4 8 11 4.6-1.6 8-6 8-11V5Zm-1 14-3-3 1.4-1.4 1.6 1.6 4.6-4.6L17 10Z",
  "global-audit": "M5 3h14v18H5Zm4 5h6v2H9Zm0 4h6v2H9Zm0 4h3v2H9Z",
  "workforce-oversight": "M8 11a3 3 0 1 0-3-3 3 3 0 0 0 3 3Zm8 0a3 3 0 1 0-3-3 3 3 0 0 0 3 3ZM3 20a5 5 0 0 1 10 0Zm8.5 0a5 5 0 0 1 9.5 0Z",
  "security-monitoring": "M12 2 4 5v6c0 5 3.4 9.4 8 11 4.6-1.6 8-6 8-11V5Zm-1 14-3-3 1.4-1.4 1.6 1.6 4.6-4.6L17 10Z",
  "platform-settings": "M19.4 13.5a7.9 7.9 0 0 0 .1-1.5 7.9 7.9 0 0 0-.1-1.5l2.1-1.6-2-3.5-2.5 1a7.6 7.6 0 0 0-2.6-1.5L14 2h-4l-.4 2.9A7.6 7.6 0 0 0 7 6.4l-2.5-1-2 3.5 2.1 1.6a7.9 7.9 0 0 0-.1 1.5 7.9 7.9 0 0 0 .1 1.5l-2.1 1.6 2 3.5 2.5-1a7.6 7.6 0 0 0 2.6 1.5L10 22h4l.4-2.9a7.6 7.6 0 0 0 2.6-1.5l2.5 1 2-3.5ZM12 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z",
  "system-monitoring": "M4 13h4l2-6 4 12 2-6h4v2h-2.6L14 23 10 11 8.5 15H4Z",
  "runtime-status": "M4 5h16v10H4Zm2 2v6h12V7Zm-2 10h16v2H4Z",
  "feature-flags": "M6 3h11l-1 5 1 5H6v8H4V3Zm2 2v6h6.6l-.7-3 .7-3Z",
  "api-health": "M7 7h10v2H7Zm0 4h10v2H7Zm0 4h6v2H7ZM4 3h16v18H4Z",
};
