import { prepareAdminOperationalExport, prepareSecurityOperationalExport } from './operationalEventService';
import type { ActiveWorkspaceRole } from '../types/auth';
import type { OperationalReportExport } from '../types/operationalSync';

type ExportOptions = {
  role: ActiveWorkspaceRole;
  reportType: string;
  format: 'CSV' | 'PDF';
};

export async function shareOperationalReport({ role, reportType, format }: ExportOptions) {
  const payload = role === 'SECURITY_GUARD'
    ? await prepareSecurityOperationalExport(reportType, format)
    : await prepareAdminOperationalExport(reportType, format);
  const filename = `${slugify(payload.title)}-${new Date(payload.generatedAt).toISOString().slice(0, 10)}`;

  if (format === 'PDF') {
    const Print = await import('expo-print');
    const Sharing = await import('expo-sharing');
    const result = await Print.printToFileAsync({ html: operationalReportHtml(payload) });
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(result.uri, { mimeType: 'application/pdf', dialogTitle: payload.title });
    }
    return payload;
  }

  const FileSystem = await import('expo-file-system/legacy');
  const Sharing = await import('expo-sharing');
  const uri = `${FileSystem.documentDirectory ?? ''}${filename}.csv`;
  await FileSystem.writeAsStringAsync(uri, operationalReportCsv(payload), { encoding: 'utf8' });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'text/csv', dialogTitle: payload.title });
  }
  return payload;
}

function operationalReportCsv(report: OperationalReportExport) {
  const columns = report.columns.length ? report.columns : inferColumns(report.rows);
  const header = columns.map((column) => csvCell(column.label)).join(',');
  const rows = report.rows.map((row) => columns.map((column) => csvCell(row[column.key])).join(','));
  return [
    `AccessFlow ${report.title}`,
    `Generated At,${csvCell(report.generatedAt)}`,
    `Generated By,${csvCell(report.generatedBy)}`,
    `Organization,${csvCell(report.organizationName || report.organizationId || 'Platform')}`,
    '',
    header,
    ...rows,
  ].join('\n');
}

function operationalReportHtml(report: OperationalReportExport) {
  const columns = report.columns.length ? report.columns : inferColumns(report.rows);
  const rows = report.rows.slice(0, 300).map((row) => (
    `<tr>${columns.map((column) => `<td>${escapeHtml(row[column.key])}</td>`).join('')}</tr>`
  )).join('');
  const summary = Object.entries(report.summary ?? {}).map(([key, value]) => (
    `<article><span>${escapeHtml(label(key))}</span><strong>${escapeHtml(value)}</strong></article>`
  )).join('');

  return `<!doctype html><html><head><meta charset="utf-8" /><style>
body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;margin:28px;background:#071120;color:#F8FAFC}
header{border-bottom:2px solid rgba(79,140,255,0.28);padding-bottom:14px;margin-bottom:18px}
h1{font-size:26px;margin:0 0 6px}p{margin:4px 0;color:#94A3B8}
section{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0}
article{border:1px solid rgba(79,140,255,0.28);border-radius:8px;padding:10px;background:#0A1628}
span{display:block;color:#94A3B8;font-size:10px;text-transform:uppercase;letter-spacing:0}
strong{display:block;font-size:18px;margin-top:6px}
table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid rgba(148,163,184,0.22);padding:6px;text-align:left;vertical-align:top}
th{background:#0B1730;color:#F8FAFC}footer{margin-top:18px;color:#94A3B8;font-size:10px}
</style></head><body><header><h1>${escapeHtml(report.title)}</h1><p>Generated ${escapeHtml(report.generatedAt)} by ${escapeHtml(report.generatedBy)}</p><p>${escapeHtml(report.organizationName || report.organizationId || 'Platform scope')}</p></header><section>${summary}</section><table><thead><tr>${columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><footer>AccessFlow operational export ${escapeHtml(report.exportId)}. Generated for audit-safe review.</footer></body></html>`;
}

function inferColumns(rows: Array<Record<string, unknown>>) {
  return Object.keys(rows[0] ?? {}).map((key) => ({ key, label: label(key) }));
}

function csvCell(value: unknown) {
  const text = value == null ? '' : String(value);
  return `"${text.replaceAll('"', '""')}"`;
}

function escapeHtml(value: unknown) {
  return String(value == null ? '' : value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function label(value: string) {
  const spaced = value.replaceAll(/([a-z])([A-Z])/g, '$1 $2').replaceAll(/[-_]+/g, ' ');
  return spaced.charAt(0).toUpperCase() + spaced.slice(1);
}

function slugify(value: string) {
  const slug = value.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-').replaceAll(/^-|-$/g, '');
  return slug || 'accessflow-report';
}
