export const enterpriseColors = {
  canvas: '#071120',
  canvasAlt: '#0A1628',
  canvasDeep: '#0B1730',
  surface: '#0A1628',
  surfaceRaised: '#0B1730',
  surfaceMuted: '#10213A',
  surfaceSubtle: '#0C1B33',
  primary: '#3B82F6',
  primaryStrong: '#2563EB',
  primaryBright: '#4F8CFF',
  primarySoft: 'rgba(59, 130, 246, 0.16)',
  primaryLine: 'rgba(79, 140, 255, 0.28)',
  accent: '#22D3EE',
  accentStrong: '#14B8A6',
  accentSoft: 'rgba(34, 211, 238, 0.13)',
  success: '#22C55E',
  successSoft: 'rgba(34, 197, 94, 0.14)',
  warning: '#F59E0B',
  warningSoft: 'rgba(245, 158, 11, 0.14)',
  danger: '#EF4444',
  dangerSoft: 'rgba(239, 68, 68, 0.14)',
  info: '#22D3EE',
  infoSoft: 'rgba(34, 211, 238, 0.12)',
  border: 'rgba(148, 163, 184, 0.16)',
  borderStrong: 'rgba(79, 140, 255, 0.28)',
  overlay: 'rgba(7, 17, 32, 0.72)',
  input: 'rgba(7, 17, 32, 0.72)',
  textPrimary: '#F8FAFC',
  textSecondary: '#94A3B8',
  textMuted: '#64748B',
  textInverse: '#F8FAFC',
} as const;

export const enterpriseStatusTones = {
  default: {
    background: 'rgba(148, 163, 184, 0.14)',
    foreground: '#CBD5E1',
    border: 'rgba(203, 213, 225, 0.24)',
    indicator: '#94A3B8',
  },
  neutral: {
    background: 'rgba(100, 116, 139, 0.14)',
    foreground: '#CBD5E1',
    border: 'rgba(203, 213, 225, 0.24)',
    indicator: '#94A3B8',
  },
  success: {
    background: 'rgba(34, 197, 94, 0.14)',
    foreground: '#BBF7D0',
    border: 'rgba(34, 197, 94, 0.32)',
    indicator: enterpriseColors.success,
  },
  warning: {
    background: 'rgba(245, 158, 11, 0.14)',
    foreground: '#FCD34D',
    border: 'rgba(252, 211, 77, 0.30)',
    indicator: enterpriseColors.warning,
  },
  danger: {
    background: 'rgba(239, 68, 68, 0.14)',
    foreground: '#FECACA',
    border: 'rgba(239, 68, 68, 0.32)',
    indicator: enterpriseColors.danger,
  },
  info: {
    background: 'rgba(34, 211, 238, 0.12)',
    foreground: '#A5F3FC',
    border: 'rgba(34, 211, 238, 0.28)',
    indicator: enterpriseColors.info,
  },
} as const;

export type EnterpriseStatusTone = keyof typeof enterpriseStatusTones;

export const enterpriseSpacing = {
  xs: 6,
  sm: 10,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
} as const;

export const enterpriseRadii = {
  sm: 8,
  md: 10,
  lg: 12,
  xl: 16,
  sheet: 24,
  pill: 999,
} as const;

export const enterpriseTypography = {
  caption: {
    fontSize: 12,
    fontWeight: '700' as const,
  },
  body: {
    fontSize: 15,
    fontWeight: '500' as const,
  },
  bodyStrong: {
    fontSize: 16,
    fontWeight: '700' as const,
  },
  title: {
    fontSize: 24,
    fontWeight: '800' as const,
  },
  heading: {
    fontSize: 20,
    fontWeight: '800' as const,
  },
  metric: {
    fontSize: 28,
    fontWeight: '800' as const,
  },
} as const;

export const enterpriseStatusLabels = {
  visitor: {
    PENDING: 'Pending approval',
    APPROVED: 'Approved',
    REJECTED: 'Denied',
    CHECKED_IN: 'Checked in',
    CHECKED_OUT: 'Checked out',
    EXPIRED: 'Expired',
    SUSPENDED: 'Suspended',
  },
  invite: {
    INVITED: 'Invited',
    PRE_REGISTRATION_PENDING: 'Pre-registration pending',
    PRE_REGISTERED: 'Pre-registered',
    PENDING_APPROVAL: 'Pending approval',
    APPROVED: 'Approved',
    BADGE_ISSUED: 'Badge issued',
    QR_ISSUED: 'Badge issued',
    REJECTED: 'Denied',
    DENIED: 'Denied',
    CHECKED_IN: 'Checked in',
    ARRIVED: 'Checked in',
    CHECKED_OUT: 'Checked out',
    EXPIRED: 'Expired',
    REVOKED: 'Revoked',
  },
  workforce: {
    ACTIVE: 'Active',
    PRESENT: 'Checked in',
    IN: 'Checked in',
    OUT: 'Checked out',
    OUTSIDE: 'Checked out',
    UNVERIFIED: 'Unverified',
    PENDING_APPROVAL: 'Pending approval',
    CHANGES_REQUESTED: 'Changes requested',
    REJECTED: 'Denied',
    DENIED: 'Denied',
    INACTIVE: 'Disabled',
    DISABLED: 'Disabled',
    LOCKED: 'Locked',
  },
} as const;

export const enterpriseStatusToneMap: Record<string, EnterpriseStatusTone> = {
  APPROVED: 'success',
  ACTIVE: 'success',
  BADGE_ISSUED: 'success',
  QR_ISSUED: 'success',
  CHECKED_IN: 'success',
  INSIDE: 'success',
  IN: 'success',
  PRESENT: 'success',
  VALID: 'success',
  SUCCESS: 'success',
  PENDING: 'warning',
  PENDING_APPROVAL: 'warning',
  PRE_REGISTERED: 'warning',
  CHANGES_REQUESTED: 'warning',
  LATE: 'warning',
  NOT_ACTIVE_YET: 'warning',
  OVERDUE_VISIT: 'warning',
  SUSPENDED: 'danger',
  WARNING: 'warning',
  REJECTED: 'danger',
  DENIED: 'danger',
  DISABLED: 'danger',
  INACTIVE: 'danger',
  LOCKED: 'danger',
  EXPIRED: 'danger',
  REVOKED: 'danger',
  CANCELLED: 'danger',
  SUSPENDED_VISITOR: 'danger',
  DANGER: 'danger',
  CHECKED_OUT: 'neutral',
  OUT: 'neutral',
  OUTSIDE: 'neutral',
  UNVERIFIED: 'neutral',
  INVITED: 'info',
  PRE_REGISTRATION_PENDING: 'info',
  SENT: 'info',
  VIEWED: 'info',
  EXPORT: 'info',
  REPORT: 'info',
  AUDIT: 'info',
  INFO: 'info',
  DEFAULT: 'neutral',
  NEUTRAL: 'neutral',
};

const enterpriseWorkflowNames = {
  visitorOperations: 'Visitor Operations',
  workforceOperations: 'Workforce Operations',
  approvalQueue: 'Approval Queue',
  liveRegister: 'Live Register',
  badgeAndQr: 'Badge and QR',
  operationalAlerts: 'Operational Alerts',
} as const;
