export const enterpriseColors = {
  canvas: '#09111E',
  canvasAlt: '#0A1322',
  surface: '#121D31',
  surfaceRaised: '#18253D',
  surfaceMuted: '#132034',
  surfaceSubtle: '#0F1728',
  primary: '#4F7CFF',
  primaryStrong: '#3765EE',
  primarySoft: 'rgba(79, 124, 255, 0.16)',
  primaryLine: 'rgba(147, 197, 253, 0.24)',
  accent: '#14B8A6',
  accentStrong: '#0F766E',
  accentSoft: 'rgba(20, 184, 166, 0.14)',
  success: '#4ADE80',
  successSoft: 'rgba(34, 197, 94, 0.14)',
  warning: '#F59E0B',
  warningSoft: 'rgba(245, 158, 11, 0.14)',
  danger: '#F87171',
  dangerSoft: 'rgba(239, 68, 68, 0.14)',
  info: '#7DD3FC',
  infoSoft: 'rgba(14, 165, 233, 0.14)',
  border: 'rgba(148, 163, 184, 0.20)',
  borderStrong: 'rgba(191, 219, 254, 0.26)',
  overlay: 'rgba(6, 10, 18, 0.68)',
  input: 'rgba(9, 16, 29, 0.82)',
  textPrimary: '#F8FBFF',
  textSecondary: '#AFBDD1',
  textMuted: '#8797AE',
  textInverse: '#FFFFFF',
} as const;

export const enterpriseStatusTones = {
  default: {
    background: 'rgba(148, 163, 184, 0.14)',
    foreground: '#CBD5E1',
    border: 'rgba(203, 213, 225, 0.24)',
    indicator: '#94A3B8',
  },
  neutral: {
    background: 'rgba(100, 116, 139, 0.14)',
    foreground: '#CBD5E1',
    border: 'rgba(203, 213, 225, 0.24)',
    indicator: '#94A3B8',
  },
  success: {
    background: 'rgba(34, 197, 94, 0.14)',
    foreground: '#86EFAC',
    border: 'rgba(134, 239, 172, 0.28)',
    indicator: enterpriseColors.success,
  },
  warning: {
    background: 'rgba(245, 158, 11, 0.14)',
    foreground: '#FCD34D',
    border: 'rgba(252, 211, 77, 0.30)',
    indicator: enterpriseColors.warning,
  },
  danger: {
    background: 'rgba(239, 68, 68, 0.14)',
    foreground: '#FCA5A5',
    border: 'rgba(252, 165, 165, 0.30)',
    indicator: enterpriseColors.danger,
  },
  info: {
    background: 'rgba(14, 165, 233, 0.14)',
    foreground: '#7DD3FC',
    border: 'rgba(125, 211, 252, 0.30)',
    indicator: enterpriseColors.info,
  },
} as const;

export type EnterpriseStatusTone = keyof typeof enterpriseStatusTones;

export const enterpriseSpacing = {
  xs: 6,
  sm: 10,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
} as const;

export const enterpriseRadii = {
  sm: 8,
  md: 10,
  lg: 12,
  xl: 16,
  sheet: 24,
  pill: 999,
} as const;

export const enterpriseTypography = {
  caption: {
    fontSize: 12,
    fontWeight: '700' as const,
  },
  body: {
    fontSize: 15,
    fontWeight: '500' as const,
  },
  bodyStrong: {
    fontSize: 16,
    fontWeight: '700' as const,
  },
  title: {
    fontSize: 24,
    fontWeight: '800' as const,
  },
  heading: {
    fontSize: 20,
    fontWeight: '800' as const,
  },
  metric: {
    fontSize: 28,
    fontWeight: '800' as const,
  },
} as const;

export const enterpriseStatusLabels = {
  visitor: {
    PENDING: 'Pending approval',
    APPROVED: 'Approved',
    REJECTED: 'Denied',
    CHECKED_IN: 'Checked in',
    CHECKED_OUT: 'Checked out',
    EXPIRED: 'Expired',
    SUSPENDED: 'Suspended',
  },
  invite: {
    INVITED: 'Invited',
    PRE_REGISTRATION_PENDING: 'Pre-registration pending',
    PRE_REGISTERED: 'Pre-registered',
    PENDING_APPROVAL: 'Pending approval',
    APPROVED: 'Approved',
    BADGE_ISSUED: 'Badge issued',
    QR_ISSUED: 'Badge issued',
    REJECTED: 'Denied',
    DENIED: 'Denied',
    CHECKED_IN: 'Checked in',
    ARRIVED: 'Checked in',
    CHECKED_OUT: 'Checked out',
    EXPIRED: 'Expired',
    REVOKED: 'Revoked',
  },
  workforce: {
    ACTIVE: 'Active',
    PRESENT: 'Checked in',
    IN: 'Checked in',
    OUT: 'Checked out',
    OUTSIDE: 'Checked out',
    UNVERIFIED: 'Unverified',
    PENDING_APPROVAL: 'Pending approval',
    CHANGES_REQUESTED: 'Changes requested',
    REJECTED: 'Denied',
    DENIED: 'Denied',
    INACTIVE: 'Disabled',
    DISABLED: 'Disabled',
    LOCKED: 'Locked',
  },
} as const;

export const enterpriseStatusToneMap: Record<string, EnterpriseStatusTone> = {
  APPROVED: 'success',
  ACTIVE: 'success',
  BADGE_ISSUED: 'success',
  QR_ISSUED: 'success',
  CHECKED_IN: 'success',
  INSIDE: 'success',
  IN: 'success',
  PRESENT: 'success',
  VALID: 'success',
  SUCCESS: 'success',
  PENDING: 'warning',
  PENDING_APPROVAL: 'warning',
  PRE_REGISTERED: 'warning',
  CHANGES_REQUESTED: 'warning',
  LATE: 'warning',
  NOT_ACTIVE_YET: 'warning',
  OVERDUE_VISIT: 'warning',
  SUSPENDED: 'warning',
  WARNING: 'warning',
  REJECTED: 'danger',
  DENIED: 'danger',
  DISABLED: 'danger',
  INACTIVE: 'danger',
  LOCKED: 'danger',
  EXPIRED: 'danger',
  REVOKED: 'danger',
  CANCELLED: 'danger',
  SUSPENDED_VISITOR: 'danger',
  DANGER: 'danger',
  CHECKED_OUT: 'info',
  OUT: 'info',
  OUTSIDE: 'info',
  UNVERIFIED: 'info',
  INVITED: 'info',
  PRE_REGISTRATION_PENDING: 'info',
  SENT: 'info',
  VIEWED: 'info',
  INFO: 'info',
  DEFAULT: 'neutral',
  NEUTRAL: 'neutral',
};

export const enterpriseWorkflowNames = {
  visitorOperations: 'Visitor Operations',
  workforceOperations: 'Workforce Operations',
  approvalQueue: 'Approval Queue',
  liveRegister: 'Live Register',
  badgeAndQr: 'Badge and QR',
  operationalAlerts: 'Operational Alerts',
} as const;
