spring:
  data:
    mongodb:
      auto-index-creation: false
  web:
    resources:
      add-mappings: false

server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 1024
  forward-headers-strategy: framework
  shutdown: graceful

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.visitor.management: INFO
    org.springframework.security: WARN
    org.mongodb.driver: WARN
